# Generated by Django 5.1.1 on 2024-10-09 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0005_alter_company_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number_gtd', models.CharField(max_length=256, verbose_name='nomer gtd')),
                ('reference_gtd', models.CharField(max_length=256)),
                ('date_recorded', models.DateField(verbose_name='qayd etilgan sana')),
                ('customs_mode', models.CharField(choices=[('IM70', 'IM 70'), ('IM40', 'IM 40'), ('ND40', 'ND 40')], max_length=10)),
                ('sender', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=256)),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('factor_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('FINISHED', 'Finished'), ('IN_PROCESS', 'In process')], max_length=15)),
                ('declarant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Dosmotr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number_gtd', models.CharField(max_length=256, verbose_name='nomer gtd')),
                ('reference_gtd', models.CharField(max_length=256)),
                ('date_recorded', models.DateField(verbose_name='qayd etilgan sana')),
                ('customs_mode', models.CharField(choices=[('IM70', 'IM 70'), ('IM40', 'IM 40'), ('ND40', 'ND 40')], max_length=10)),
                ('sender', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=256)),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('factor_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('FINISHED', 'Finished'), ('IN_PROCESS', 'In process')], max_length=15)),
                ('declarant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
