# Generated by Django 5.1.1 on 2024-10-09 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dosmotr',
            name='declarant',
        ),
        migrations.RemoveField(
            model_name='dosmotr',
            name='reciever',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='Dosmotr',
        ),
    ]
