# Generated by Django 5.1.1 on 2024-09-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='number_gtd',
            field=models.CharField(max_length=256, verbose_name='nomer gtd'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='status',
            field=models.CharField(choices=[('FINISHED', 'Finished'), ('IN_PROCESS', 'In process')], max_length=15),
        ),
    ]
